Update 1049-1130 【Industrial Foregoing 工业先锋】.json
Addyabbia/FTB_Skies_Expert_ZH_CN pull request #27
Opened 2024-02-23 06:12 UTC by creeball

2024-02-23 22:47 UTC, Addyabbia requested changes

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests11.description4": "Additionally, to make Ether Gas, the Fluid Laser &6must be over a Wither&r. This is a bit tricky to do, but the &6Stasis Chamber&r wo
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests11.description4": "此外，要制作以太气体，流体镭射钻基座&6必须放在凋零&r上方。这有点难做，但用&6冷凝室&r会更容易点",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests11.description6": "Laser Bases are not powered directly. Instead, a &bLaser Drill&r is placed 1 block away, and &othat&r is given power.[--镭射站基座并不是直接供能的
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests11.description6": "镭射站基座不可以直接供能。将&b镭射钻&r放置在1个方块外，&o镭射钻&r会为其供能",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests11.tasks0.title": "Laser Bases[--镭射钻基座--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests11.tasks0.title": "镭射钻基座",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests12.subtitle": "Supremium[--终极--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests12.subtitle": "超级",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests12.description": "&bSupremium Machine Frames&r are used to craft the greatest tier of machines.[--&b终极机器框架&r用于制作最高级的机器.--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests12.description": "&b超级机器框架&r用于制作最高级的机器",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests13.subtitle": "Make a Plant Fertilizer[--做一个施肥机--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests13.subtitle": "制作施肥机",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests13.description": "The &bPlant Fertilizer&r will &6fertilize crops&r using Bone Meal or Fertilizer.[--&b施肥机&r使用骨粉或肥料&6施肥&r.--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests13.description": "&b施肥机&r使用骨粉或肥料&6施肥&r",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests14.subtitle": "Make an enchanting machine[--做一个附魔机--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests14.subtitle": "制作自动附魔台",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests14.description0": "The &bEnchantment Factory&r will &6use Essence to enchant items&r, equivalent to 30 levels of experience.[--&b自动附魔台&r可以&6使用精华附魔物品&r,相
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests14.description0": "&b自动附魔台&r可以&6使用精华附魔物品&r，相当于30级的经验",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
>  	"ftbquests.chapter.industrial_foregoing.quests14.description2": "The &bEnchantment Extractor&r will destroy enchanted items, either moving the enchantments into Books, or converting them directly to
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests14.description2": "&b附魔提取机&r将销毁附魔物品，将附魔转移到书中或是直接转化为精华",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests14.description4": "Completing either task will complete the task.[--完成任意一个都会完成任务.--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests14.description4": "完成任意一个都会完成任务",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests15.subtitle": "Make a Mob Crusher[--做个屠宰机--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests15.subtitle": "制作屠宰机",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests15.description0": "The &bMob Crusher&r will kill mobs in its working area, &6collecting the drops&r and converting the xp into &6Essence&r.[--&b屠宰机&r会杀死
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests15.description0": "&b屠宰机&r会杀死其工作区域内的生物，&6收集掉落物&r并将经验转化为&6精华&r",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests15.description2": "Optionally, you can set it to not generate Essence, and instead &6apply Looting&r.[--你可以选择将其设置为不产生精华,而是&6施加抢夺&r.--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests15.description2": "你可以选择将其设置为不产生精华，而是&6施加抢夺&r效果",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests16.subtitle": "Watch for flies![--看苍蝇!--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests16.subtitle": "小心苍蝇！",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests16.description0": "The &bMob Duplicator&r will &6clone a specific mob, using Essence&r.[--&b自动刷怪机&r会&6使用精华液&r对特定生物进行&6克隆.--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests16.description0": "&b自动刷怪机&r会&6使用精华液复制&r特定生物&6",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests16.description2": "Specify the mob by inserting a filled &bMob Imprisonment Device&r.[--放入一个捕获的&b大师球&r指定生物.--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests16.description2": "放入一个已捕获生物的&b大师球&r指定生物",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
>  	"ftbquests.chapter.industrial_foregoing.quests17.subtitle": "Cursed Earth[--诅咒之土--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests17.subtitle": "诅咒之土",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests17.description0": "&bMechanical Dirt&r will &6rapidly spawn hostile mobs&r when provided FE and &6Liquid Meat&r.[--&b机械诅咒之土&r在提供FE和&6肉汤&r时会&6快速生成敌对生物&r.
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests17.description0": "&b机械诅咒之土&r在提供FE和&6肉汤&r时会&6快速生成敌对生物&r",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests17.description2": "If you place multiple adjacent, the Meat will be equally distributed.[--如果你连续放置多个,肉汤就会平均被分配.--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests17.description2": "如果你连续放置多个，肉汤就会平均被分配",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests18.title": "Addons[--插件--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests18.title": "插件",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
>  	"ftbquests.chapter.industrial_foregoing.quests18.subtitle": "Machine upgrades[--机器升级--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests18.subtitle": "机器升级",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests18.description0": "&bAddons&r can be installed onto machines to make them work better in some way.[--&b插件&r可以安装在机器上,增强它们在某方面的工作.--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests18.description0": "&b插件&r可以安装在机器上，增强它们在某项工作的速度",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests18.description2": "&bRange Addons&r &6increase the work area&r of machines, by one additional block per tier.[--&b范围升级插件&r&6每级增加机器一个方块的工作区域&r.--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests18.description2": "&b范围升级插件&r&6每级增加机器一个方块的工作区域&r",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests18.description4": "The three types of &bRange Addon&r make machines &6work faster&r, in three separate ways.[--三种类型的&b速度升级插件&r可以让机器&6工作得更快&r,分别是有三种不同的方式
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests18.description4": "三种类型的&b速度升级插件&r可以让机器&6工作得更快&r，分别是有三种不同的方式",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests18.tasks0.title": "Range Addons[--范围升级插件--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests18.tasks0.title": "范围升级插件",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests18.tasks1.title": "Speed Addons[--速度升级插件--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests18.tasks1.title": "速度升级插件",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests19.subtitle": "Meat Injections[--肉汤注射--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests19.subtitle": "肉汤注射器",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests19.description": "The &bMeat Feeder&r, while supplied with Liquid Meat, will &6automatically keep you fully fed&r while anywhere in your inventory.[--&b
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests19.description": "&b肉汤注射器&r在供应肉汤时，放在你的物品栏里会&6自动喂食保持饱腹&r",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests20.title": "Infinity Tools[--无限工具--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests20.title": "无限工具",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests20.description0": "The &bInfinity Tools&r are &6powered by Biofuel&r, but &6become more powerful the more FE they have&r.[--&b无限工具&r由&6生物燃料供能&r,但&6FE能量越
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests20.description0": "&b无限工具&r由&6生物燃料供能&r，&6FE能量越多&r就越强大",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests20.description2": "There are 7 tiers, each costing exponentially more FE than the previous, but also becoming exponentially more powerful.[--有7个等级,每个等级的
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests20.description2": "一共有7个等级，每个等级所需的 FE 都成倍增加，其威力也成倍增加",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests20.tasks0.title": "Infinity Tools[--无限工具--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests20.tasks0.title": "无限工具",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests21.subtitle": "What do you mean, Drawers exist?[--你什么意思,为什么不用抽屉?--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests21.subtitle": "抽屉存在的意义是什么？",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests21.description0": "&bBlack Hole Units&r store a massive amount of a single item. Higher tiers store more.[--&b黑洞存储单元&r存储大量单种物品。越高的等级存储越多.--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests21.description0": "&b黑洞存储单元&r可以存储大量单种物品。等级越高存储越多",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests21.description2": "The same is true for &bBlack Hole Tanks&r, but for fluids instead of items.[--&b黑洞储液罐&r也是一样,但存储流体而不是物品。--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests21.description2": "&b黑洞储液罐&r也是一样，但存储的是流体而不是物品",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests21.tasks0.title": "Black Hole Units[--黑洞存储单元--]",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests21.tasks0.title": "黑洞存储单元",
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests21.tasks1.title": "Black Hole Tanks[--黑洞储液罐--]"
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests21.tasks1.title": "黑洞储液罐"
```

2024-02-23 22:47 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"_comment": "译者：莱达  校对：",
```suggestion
	"_comment_industrial_foregoing": "译者：莱达  校对：Addyabbia",
```

2024-02-24 02:16 UTC, Addyabbia requested changes

2024-02-24 02:16 UTC, Addyabbia commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +    "ftbquests.chapter.industrial_foregoing.quests4.subtitle": "没有笑声就无法屠宰",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests4.subtitle": "没有笑声就无法屠宰",
```

2024-02-24 02:18 UTC, Addyabbia approved these changes

2024-02-24 14:19 UTC, SlimeSB approved these changes

2024-02-24 14:19 UTC, SlimeSB commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests4.subtitle": "没有笑声就无法屠宰",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests4.subtitle": "“鲜血，杀戮，使我沸腾！”",
```
没活可以抄三国杀台词

2024-02-24 14:19 UTC, SlimeSB commented on FTBQ_lang/1049-1130 【Industrial Foregoing 工业先锋】.json
> +	"ftbquests.chapter.industrial_foregoing.quests16.description2": "放入一个已捕获生物的&b大师球&r指定生物",
```suggestion
	"ftbquests.chapter.industrial_foregoing.quests16.description2": "放入一个已捕获生物的&b生物捕获工具&r指定生物",
```

2024-02-24 14:22 UTC, merged