更新 1534-1570 【Overpowered!】.json
Addyabbia/FTB_Skies_Expert_ZH_CN pull request #29
Opened 2024-02-23 17:37 UTC by Addyabbia

2024-02-23 22:51 UTC, Addyabbia commented
可能会涉及的内容：
Ender Trigon：https://www.mcmod.cn/class/7988.html

2024-02-25 02:03 UTC, SlimeSB requested changes

2024-02-25 02:03 UTC, SlimeSB commented on FTBQ_lang/1534-1570 【Overpowered!】.json
> +	"ftbquests.chapter.overpowered.quests13.title": "黑曜石技术带来的乐趣",
```suggestion
	"ftbquests.chapter.overpowered.quests13.title": "黑曜石科技乐事",
```

2024-02-25 02:03 UTC, SlimeSB commented on FTBQ_lang/1534-1570 【Overpowered!】.json
> +	"ftbquests.chapter.overpowered.quests22.subtitle": "鳍",
```suggestion
	"ftbquests.chapter.overpowered.quests22.subtitle": "完结",
```

2024-02-26 07:16 UTC, merged